/**
 * Gallery images are stored full size on Cloudinary (often several MB). Discord's media proxy
 * struggles with those, especially when an embed is edited (the image ends up with 0x0 size and
 * isn't rendered), so embeds use a resized, compressed rendition generated by Cloudinary.
 */

const CLOUDINARY_UPLOAD = /^(https:\/\/res\.cloudinary\.com\/[^/]+\/image\/upload\/)(.+)$/;
const EMBED_TRANSFORMATION = 'c_limit,w_1600,f_jpg,q_auto';

export const embedImageUrl = (url: string) => {
  const match = url.match(CLOUDINARY_UPLOAD);
  // Keep GIFs untouched so they stay animated
  if (!match || /\.gif$/i.test(url)) return url;
  return `${match[1]}${EMBED_TRANSFORMATION}/${match[2]}`;
};
