import { AttachmentBuilder } from 'discord.js';

/**
 * Gallery images are stored full size on Cloudinary (often several MB). Embeds use a resized,
 * compressed rendition generated by Cloudinary instead.
 */

const CLOUDINARY_UPLOAD = /^(https:\/\/res\.cloudinary\.com\/[^/]+\/image\/upload\/)(.+)$/;
const EMBED_TRANSFORMATION = 'c_limit,w_1600,f_jpg,q_auto';
/** Stay well under Discord's upload limit. */
const MAX_ATTACHMENT_BYTES = 8 * 1024 * 1024;
const DOWNLOAD_TIMEOUT_MS = 5000;

const isGif = (url: string) => /\.gif$/i.test(new URL(url).pathname);

export const embedImageUrl = (url: string) => {
  const match = url.match(CLOUDINARY_UPLOAD);
  // Keep GIFs untouched so they stay animated
  if (!match || isGif(url)) return url;
  return `${match[1]}${EMBED_TRANSFORMATION}/${match[2]}`;
};

export interface EmbedImage {
  /** Value for `EmbedBuilder#setImage`. */
  url: string;
  /** File to send with the message when the image is uploaded as an attachment. */
  file?: AttachmentBuilder;
}

/**
 * Downloads the image and returns it as an attachment referenced by the embed
 * (`attachment://...`). When a message is edited, Discord renders images that point to external
 * URLs unreliably (the client often keeps showing no image), while uploaded attachments show up
 * immediately. Falls back to the plain URL if the download fails or the file is too big.
 */
export const resolveEmbedImage = async (sourceUrl: string, name = 'image'): Promise<EmbedImage> => {
  const url = embedImageUrl(sourceUrl);
  const fileName = `${name}.${isGif(url) ? 'gif' : 'jpg'}`;

  try {
    const response = await fetch(url, { signal: AbortSignal.timeout(DOWNLOAD_TIMEOUT_MS) });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const buffer = Buffer.from(await response.arrayBuffer());
    if (buffer.length > MAX_ATTACHMENT_BYTES) return { url };
    return { url: `attachment://${fileName}`, file: new AttachmentBuilder(buffer, { name: fileName }) };
  } catch (error) {
    console.warn(`[Images] Could not download ${url}, using the URL instead:`, (error as Error).message);
    return { url };
  }
};
